### Create
POST http://localhost:8082/products-service/products
Content-Type: application/json

{
  "title": "Mac",
  "price": 7886,
  "amount": 23
}

### Get all
GET http://localhost:8082/products-service/products