### Create
POST http://localhost:8082/products-service/products
Content-Type: application/json

{
  "title": "CD",
  "price": 365,
  "amount": 1500
}

### Get all
GET http://localhost:8082/products-service/products