### Create
POST http://localhost:8082/orders-service/orders
Content-Type: application/json

{
  "productId": "f241af45-4854-43f4-95bc-ab54da338a29",
  "quantity": 1,
  "addressId": "afbb5881-a872-4d13-993c-faeb8350eea5"
}